batch_size: 128
eval_fs_epoch: 5
fs_dataset: test_casme2
fs_dataset_args:
  split: test
load_encoder: ./save/im800-resnet18.pth
max_epoch: 100
model: classifier
model_args:
  classifier: linear-classifier
  classifier_args:
    n_classes: 7
  encoder: resnet18
  encoder_args: {}
optimizer: sgd
optimizer_args:
  lr: 0.01
  milestones:
  - 90
  weight_decay: 0.0005
save_epoch: 5
train_dataset: train_ck+
train_dataset_args:
  augment: resize
  split: train
val_dataset: test_ck+
val_dataset_args:
  split: train_phase_val
visualize_datasets: true
